# Generated by Django 5.1.2 on 2026-02-07 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motions', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='motionvote',
            new_name='motions_mot_motion__c3806d_idx',
            old_name='motions_mot_motion__9bfda0_idx',
        ),
    ]
