# Generated by Django 5.1.2 on 2024-11-03 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='session_id',
            new_name='session',
        ),
    ]
