# Generated by Django 5.1.2 on 2024-11-03 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0002_rename_session_id_voter_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='session',
            new_name='session_id',
        ),
    ]
