# Generated by Django 5.1.2 on 2024-11-10 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0004_rename_session_id_voter_session'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votingsegmentheader',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='votingsegmentheader',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
