# Generated by Django 5.1.2 on 2024-11-15 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0005_alter_votingsegmentheader_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingsession',
            name='current_voters',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='votingsession',
            name='total_voters',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='votingsession',
            name='unique_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='votingsession',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
