# Generated by Django 5.1.2 on 2024-12-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0008_alter_voter_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voter',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
