# Generated by Django 5.1.2 on 2024-12-03 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0009_voter_is_finished_voter_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='is_finished',
            new_name='has_finished',
        ),
    ]
