# Generated by Django 5.1.2 on 2024-12-24 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0010_rename_is_finished_voter_has_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='total_votes',
            field=models.IntegerField(default=0),
        ),
    ]
