# Generated by Django 5.1.2 on 2025-09-23 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0011_candidate_total_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='candidate_photos/'),
        ),
    ]
