# Generated by Django 5.1.2 on 2025-10-18 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0015_enforce_session_uuid_unique'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ballot',
            new_name='voters_ball_session_33902a_idx',
            old_name='voters_ballot_session_segment_idx',
        ),
    ]
