# Generated by Django 5.1.2 on 2025-12-13 18:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0017_manualcheckcard_ballot_bundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='voter',
            name='registered_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='voter',
            name='registration_source',
            field=models.CharField(choices=[('admin', 'Admin/Manual'), ('import', 'Import'), ('self', 'Self-Registration')], db_index=True, default='admin', max_length=32),
        ),
        migrations.AddField(
            model_name='voter',
            name='registration_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='approved', max_length=16),
        ),
        migrations.AddField(
            model_name='votingsession',
            name='allow_self_registration',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='votingsession',
            name='auto_approve_self_registration',
            field=models.BooleanField(default=False),
        ),
    ]
